# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ip_to_address_pb2 as ip__to__address__pb2


class IpToAddressStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Location = channel.unary_unary(
        '/IpToAddress/Location',
        request_serializer=ip__to__address__pb2.IP.SerializeToString,
        response_deserializer=ip__to__address__pb2.IP.FromString,
        )


class IpToAddressServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Location(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IpToAddressServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Location': grpc.unary_unary_rpc_method_handler(
          servicer.Location,
          request_deserializer=ip__to__address__pb2.IP.FromString,
          response_serializer=ip__to__address__pb2.IP.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'IpToAddress', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
